{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 RespondentID\n",
      "1 Seen_any\n",
      "2 Fan_of_Star_War_Franchise\n",
      "3 Seen_1\n",
      "4 Seen_2\n",
      "5 Seen_3\n",
      "6 Seen_4\n",
      "7 Seen_5\n",
      "8 Seen_6\n",
      "9 Ranking_1\n",
      "10 Ranking_2\n",
      "11 Ranking_3\n",
      "12 Ranking_4\n",
      "13 Ranking_5\n",
      "14 Ranking_6\n",
      "15 Han Solo\n",
      "16 Luke Skywalker\n",
      "17 Princess Leia Organa\n",
      "18 Anakin Skywalker\n",
      "19 Obi Wan Kenobi\n",
      "20 Emperor Palpatine\n",
      "21 Darth Vader\n",
      "22 Lando Calrissian\n",
      "23 Boba Fett\n",
      "24 C-3P0\n",
      "25 R2 D2\n",
      "26 Jar Jar Binks\n",
      "27 Padme Amidala\n",
      "28 Yoda\n",
      "29 Character shot first\n",
      "30 Familiarity with Expanded Universe\n",
      "31 Fan_of_Expanded_Universe\n",
      "32 Fan_of_Star_Trek_Franchise\n",
      "33 Gender\n",
      "34 Age\n",
      "35 Household Income\n",
      "36 Education\n",
      "37 Location (Census Region)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "Text(0.5,1,'Ranking of each episode, 1: highest')"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import re\n",
    "\n",
    "#PartI: Reading and cleansing the data\n",
    "\n",
    "#read the data\n",
    "star_wars = pd.read_csv(\"StarWars.csv\", encoding=\"ISO-8859-1\")\n",
    "\n",
    "#display the columns \n",
    "star_wars.head()\n",
    "star_wars.shape # number of rows: 1187, number of columns: 38\n",
    "#for k, v in enumerate(star_wars.columns): \n",
    "#    print(k,v)\n",
    "    \n",
    "#we can check the columns name using index, and then display the column content to get a sense of what the columns is about\n",
    "star_wars[star_wars.columns[15]]\n",
    "\n",
    "#for columns 3 to 8, the first row is the episode to be asked about on whether it has been watched\n",
    "#for columns 9 to 14, the first row is the episode to be ranked\n",
    "#for columns 15 to 28, the first row is the character to be asked about for preference \n",
    "\n",
    "#rename the columns 3-14, 29-33 for easy interpretation\n",
    "star_wars = star_wars.rename(columns = {\n",
    "    \"Have you seen any of the 6 films in the Star Wars franchise?\": \"Seen_any\",\n",
    "    \"Do you consider yourself to be a fan of the Star Wars film franchise?\": \"Fan_of_Star_War_Franchise\",\n",
    "    \"Which of the following Star Wars films have you seen? Please select all that apply.\": \"Seen_1\",\n",
    "    \"Unnamed: 4\": \"Seen_2\",\n",
    "    \"Unnamed: 5\": \"Seen_3\",\n",
    "    \"Unnamed: 6\": \"Seen_4\",\n",
    "    \"Unnamed: 7\": \"Seen_5\",\n",
    "    \"Unnamed: 8\": \"Seen_6\",  \n",
    "    \"Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.\": \"Ranking_1\", \n",
    "    \"Unnamed: 10\": \"Ranking_2\",\n",
    "    \"Unnamed: 11\": \"Ranking_3\",\n",
    "    \"Unnamed: 12\": \"Ranking_4\",\n",
    "    \"Unnamed: 13\": \"Ranking_5\",\n",
    "    \"Unnamed: 14\": \"Ranking_6\",\n",
    "    \"Which character shot first?\": \"Character shot first\",\n",
    "    \"Are you familiar with the Expanded Universe?\": \"Familiarity with Expanded Universe\",\n",
    "    \"Do you consider yourself to be a fan of the Expanded Universe?æ\": \"Fan_of_Expanded_Universe\",\n",
    "    \"Do you consider yourself to be a fan of the Star Trek franchise?\": \"Fan_of_Star_Trek_Franchise\"\n",
    "})\n",
    "\n",
    "#for columns 15-28, get the character from the first row, create a dictionary for the new column names, and use it to rename the columns \n",
    "rename_dict_character = {}\n",
    "for k,v in enumerate(star_wars.iloc[0,15:29].tolist()): \n",
    "    rename_dict_character[star_wars.columns[k+15]] = v\n",
    "star_wars = star_wars.rename(columns = rename_dict_character)\n",
    "\n",
    "#check the renamed column names\n",
    "for k, v in enumerate(star_wars.columns): \n",
    "    print(k,v)\n",
    "\n",
    "#create the function to check the unique values and the count of each value in a series \n",
    "def content(series):\n",
    "    u = series.unique()\n",
    "    c = series.value_counts()\n",
    "    return u,c\n",
    "\n",
    "#apply the function to each column of the dataframe \n",
    "check = star_wars.apply(lambda x:content(x))\n",
    "\n",
    "#clean RespondentID column \n",
    "check[0]\n",
    "star_wars = star_wars.loc[star_wars[\"RespondentID\"].notnull()]\n",
    "star_wars.shape # number of rows: 1186, number of columns: 38\n",
    "#only one row of NaN is removed \n",
    "#get the new unique values and counts for the new dataframe \n",
    "check = star_wars.apply(lambda x:content(x))\n",
    "\n",
    "#convert Yes & No response into True & False\n",
    "def convert(series,input_1, input_2):\n",
    "    yes_no = {\n",
    "        input_1: True,\n",
    "        input_2: False\n",
    "    }\n",
    "    series = series.map(yes_no)\n",
    "    return series\n",
    "\n",
    "'''the 4 columns with yes,no,nan as responses: \n",
    "1 Seen_any                                                        ([Yes, No], [936, 250])\n",
    "2 Fan_of_Star_War_Franchise                                  ([Yes, nan, No], [552, 284])\n",
    "30 Familiarity with Expanded Universe                         ([Yes, nan, No], [615, 213])\n",
    "31 Fan_of_Expanded_Universe                                    ([No, nan, Yes], [114, 99])\n",
    "32 Fan_of_Star_Trek_Franchise                                 ([No, Yes, nan], [641, 427])\n",
    "'''\n",
    "#apply the conversion of YN to TF to the above 5 columns\n",
    "star_wars.iloc[:,[1,2,30,31,32]] = star_wars.iloc[:,[1,2,30,31,32]].apply(lambda x: convert(x,\"Yes\",\"No\"))\n",
    "#get the new unique values and counts for the new dataframe \n",
    "check = star_wars.apply(lambda x:content(x))\n",
    "check\n",
    "star_wars.head()\n",
    "#for columns \"Seen_1\" to \"Seen_6\", when column value = espisode name, it means Yes. \n",
    "#do the conversion \n",
    "convert_list = {\n",
    "    \"Seen_1\": \"Star Wars: Episode I  The Phantom Menace\", \n",
    "    \"Seen_2\": \"Star Wars: Episode II  Attack of the Clones\",\n",
    "    \"Seen_3\": \"Star Wars: Episode III  Revenge of the Sith\",\n",
    "    \"Seen_4\": \"Star Wars: Episode IV  A New Hope\",\n",
    "    \"Seen_5\": \"Star Wars: Episode V The Empire Strikes Back\",\n",
    "    \"Seen_6\": \"Star Wars: Episode VI Return of the Jedi\"\n",
    "    }\n",
    "for k,v in convert_list.items():\n",
    "     star_wars.loc[:,k] = convert(star_wars.loc[:,k],v,\"No\") \n",
    "    #to use apply, it has to be dataframe but not one column (series)\n",
    "    #for series, just use the function directly on it     \n",
    "check = star_wars.apply(lambda x:content(x))\n",
    "check\n",
    "\n",
    "#convert ranking into float for easy calculation of statistics\n",
    "star_wars.iloc[:,9:15].apply(lambda x: x.astype(float))\n",
    "\n",
    "check = star_wars.apply(lambda x:content(x))\n",
    "check[15]\n",
    "\n",
    "''' columns 15-28 have values as follows:\n",
    " Somewhat favorably                             \n",
    " Neither favorably nor unfavorably (neutral)     \n",
    " Unfamiliar (N/A)                                \n",
    " Somewhat unfavorably                           \n",
    " Very unfavorably   \n",
    " nan\n",
    " '''\n",
    "#no data cleansing required for columns 15-28 as we can use the values for filtering and plotting graphs\n",
    "\n",
    "check[29]\n",
    "star_wars[\"Character shot first\"].isnull().sum()\n",
    "#column 29 would be ignored in analysis since 306 respondents do not understand the questions (~26%), and\n",
    "#358 missing values (~30%)\n",
    "\n",
    "#check the counts of missing values in each column\n",
    "star_wars.isnull().sum()\n",
    "\n",
    "check[33]\n",
    "#Male: 549 (42%)\n",
    "#Female: 497 (58%)\n",
    "\n",
    "check[34]\n",
    "#18-29: 218 (21%)\n",
    "#30-44: 268 (26%)\n",
    "#45-60: 291 (28%)\n",
    "#>60: 269 (25%)\n",
    "\n",
    "check[35]\n",
    "#$150,000+: 95 (11%)\n",
    "#$50,000 - $99,999: 298 (35%)\n",
    "#$25,000 - $49,999: 186 (22%)\n",
    "#$100,000 - $149,999: 141 (16%)\n",
    "#$0 - $24,999: 138 (16%)\n",
    "\n",
    "check[36]\n",
    "#Some college or Associate degree: 328 (32%)\n",
    "#Bachelor degree: 321 (31%)\n",
    "#Graduate degree: 275 (27%)\n",
    "#High school degree: 105 (10%)\n",
    "#Less than high school degree: 7 (0%)\n",
    "\n",
    "\n",
    "#PartII: Creating datasets for different segments \n",
    "#creating datasets for male and female \n",
    "star_wars_m = star_wars.loc[star_wars[\"Gender\"] == \"Male\"]\n",
    "star_wars_f = star_wars.loc[star_wars[\"Gender\"] == \"Female\"]\n",
    "seen_m = star_wars_m.iloc[:,3:9]\n",
    "seen_f = star_wars_f.iloc[:,3:9]\n",
    "\n",
    "\n",
    "#creating datasets & lists for plotting - by education level \n",
    "star_wars_graduate = star_wars.loc[star_wars[\"Education\"] == \"Graduate degree\"]\n",
    "star_wars_bachelor = star_wars.loc[star_wars[\"Education\"] == \"Bachelor degree\"]\n",
    "star_wars_college = star_wars.loc[star_wars[\"Education\"] == \"Some college or Associate degree\"]\n",
    "star_wars_high = star_wars.loc[star_wars[\"Education\"] == \"High school degree\"]\n",
    "star_wars_less = star_wars.loc[star_wars[\"Education\"] == \"Less than high school degree\"]\n",
    "\n",
    "list_education = [star_wars_less, star_wars_high, star_wars_college, star_wars_bachelor, star_wars_graduate]\n",
    "labellist_education = [\"Less\", \"High\", \"College\", \"Bachelor\", \"Graduate\"]\n",
    "colorlist_education = [\"bisque\", \"tan\", \"darksalmon\", \"coral\", \"sienna\"]\n",
    "\n",
    "#creating datasets & lists for plotting - by income level \n",
    "star_wars_0_24999 = star_wars.loc[star_wars[\"Household Income\"] == \"$0 - $24,999\"]\n",
    "star_wars_25000_49999 = star_wars.loc[star_wars[\"Household Income\"] == \"$25,000 - $49,999\"]\n",
    "star_wars_50000_99999 = star_wars.loc[star_wars[\"Household Income\"] == \"$50,000 - $99,999\"]\n",
    "star_wars_100000_1499999 = star_wars.loc[star_wars[\"Household Income\"] == \"$100,000 - $149,999\"]\n",
    "star_wars_150000 = star_wars.loc[star_wars[\"Household Income\"] == \"$150,000+\"]\n",
    "list_income = [star_wars_0_24999, star_wars_25000_49999, star_wars_50000_99999, star_wars_100000_1499999, star_wars_150000]\n",
    "labellist_income = [\"0-24999\", \"25000-49999 \",\"50000-99999\", \"100000-1499999\", \"150000+\"]\n",
    "colorlist_income = [\"lightgreen\", \"mediumseagreen\", \"seagreen\", \"g\", \"darkgreen\"]\n",
    "\n",
    "#creating datasets & lists for plotting -  by age \n",
    "star_wars_18_29 = star_wars.loc[star_wars[\"Age\"] == \"18-29\"]\n",
    "star_wars_30_44 = star_wars.loc[star_wars[\"Age\"] == \"30-44\"]\n",
    "star_wars_45_60 = star_wars.loc[star_wars[\"Age\"] == \"45-60\"]\n",
    "star_wars_60 = star_wars.loc[star_wars[\"Age\"] == \"> 60\"]\n",
    "list_age = [star_wars_18_29, star_wars_30_44, star_wars_45_60, star_wars_60]\n",
    "labellist_age = [\"18-29\", \"30-44\",\"45-60\",\"60+\"]\n",
    "colorlist_age = [\"paleturquoise\", \"skyblue\", \"c\", \"dodgerblue\"]\n",
    "\n",
    "#creating the function to select certain columns from the star_wars dataset\n",
    "def select(df, start_col, end_col):\n",
    "    df_new = df.iloc[:,start_col:(end_col+1)]\n",
    "    return df_new\n",
    "\n",
    "list_education_select = []\n",
    "list_income_select = []\n",
    "list_age_select = []\n",
    "\n",
    "for each in list_education: \n",
    "    s = select(each,3,8)\n",
    "    list_education_select.append(s)  \n",
    "\n",
    "for each in list_income: \n",
    "    s = select(each,3,8)\n",
    "    list_income_select.append(s)  \n",
    "    \n",
    "for each in list_age: \n",
    "    s = select(each,3,8)\n",
    "    list_age_select.append(s) \n",
    "\n",
    "    \n",
    "ranking_select = select(star_wars,9,15)\n",
    "\n",
    "#creating list of episode names \n",
    "ep = convert_list.values()\n",
    "ep_name_list = []\n",
    "for name in ep: \n",
    "    ep_name = re.findall(\"Episode.*[VI]\", name)\n",
    "    ep_name = \"\".join(ep_name) #remove the list property of each found value \n",
    "    ep_name_list.append(ep_name)\n",
    "\n",
    "#PartIII: Analysing the data\n",
    "#1: comparing popularity among espisodes, by demographics\n",
    "seen = star_wars.iloc[:,3:9]\n",
    "check[3:9] # only True and nan in the columns, meaning that nan refers to havent watched that episode \n",
    "\n",
    "fig, ax = plt.subplots(1,1, figsize = (5,5))\n",
    "ind = np.arange(6)\n",
    "sns.set(style =\"whitegrid\")\n",
    "g = sns.barplot(ind,seen.sum())\n",
    "ax.set_xticklabels(ep_name_list)\n",
    "ax.set_title(\"Which episodes have respondents watched\")\n",
    "#adding text to bar (TBD)\n",
    "\n",
    "f, ax = plt.subplots(figsize = (5,5), sharey = True)\n",
    "ind = np.arange(6)\n",
    "g = ax.bar(ind,seen_m.sum(),color=\"cadetblue\",width = 0.3, label = \"Male\")\n",
    "ax.set_title(\"Which episodes have respondents watched_by Gender\")\n",
    "\n",
    "ind = ind + 0.3 #shifting the 2nd plot's bars to the right \n",
    "g = ax.bar(ind ,seen_f.sum(), color = \"palevioletred\", width = 0.3, label = \"Female\")\n",
    "ax.set_xticklabels(ep_name_list)\n",
    "ax.set_xticks(ind) #if not set, the xticks will start from 0.3, affecting the xticklabels (use ax.get_xticks() for tick position) \n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "#approximate same distribution for male and female \n",
    "#\"Star Wars: Episode V The Empire Strikes Back\" is the one watched by most respondents  \n",
    "    \n",
    "f, ax = plt.subplots(figsize = (10,5), sharey = True)\n",
    "ind = np.arange(6)\n",
    "for k,v in enumerate(list_education_select): \n",
    "    ax.bar(ind, v.sum(), color = colorlist_education[k], width = 0.17, label = labellist_education[k])\n",
    "    ind = ind + 0.17\n",
    "ax.legend(bbox_to_anchor=(1.15, 0.6)) #adjust bbox_to_anchor for position of legend outside graph\n",
    "ax.set_xticklabels(ep_name_list)\n",
    "ax.set_xticks(ind-0.5) #adjust the position of xticks\n",
    "ax.set_title(\"Which episodes have respondents watched_by Education Level\")\n",
    "\n",
    "f, ax = plt.subplots(figsize = (10,5), sharey = True)\n",
    "ind = np.arange(6)\n",
    "for k,v in enumerate(list_income_select): \n",
    "    ax.bar(ind, v.sum(), color = colorlist_income[k], width = 0.17, label = labellist_income[k])\n",
    "    ind = ind + 0.17\n",
    "ax.legend(bbox_to_anchor=(1, 0.6)) #adjust bbox_to_anchor for position of legend outside graph\n",
    "ax.set_xticklabels(ep_name_list)\n",
    "ax.set_xticks(ind-0.5) #adjust the position of xticks\n",
    "ax.set_title(\"Which episodes have respondents watched_by Income Level\")\n",
    "\n",
    "\n",
    "f, ax = plt.subplots(figsize = (10,5), sharey = True)\n",
    "ind = np.arange(6)\n",
    "for k,v in enumerate(list_age_select): \n",
    "    ax.bar(ind, v.sum(), color = colorlist_age[k], width = 0.17, label = labellist_age[k])\n",
    "    ind = ind + 0.17\n",
    "ax.legend(bbox_to_anchor=(1, 0.6)) #adjust bbox_to_anchor for position of legend outside graph\n",
    "ax.set_xticklabels(ep_name_list)\n",
    "ax.set_xticks(ind-0.5) #adjust the position of xticks\n",
    "ax.set_title(\"Which episodes have respondents watched_by Age Level\")\n",
    "\n",
    "\n",
    "#corr between favorite characeter and episode watched, age, income, education level \n",
    "#heatmap\n",
    "f, ax = plt.subplots(figsize = (10,5))\n",
    "sns.boxplot(data = ranking_select)\n",
    "sns.swarmplot(data = ranking_select)\n",
    "ax.set_xticklabels(ep_name_list)\n",
    "ax.set_title(\"Ranking of each episode, 1: highest\")\n",
    "#Episode V is the most watched and also rated the highest \n",
    "\n"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
